/*
Copyright (c) 2023 by Steffen Kühn, steffen.kuehn@aurinovo.de

This file is part of OpenWME, an electromagnetic field solver based on
Weber-Maxwell electrodynamics.

OpenWME is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

OpenWME is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
*/

#include <stdio.h>
#include <math.h>
#include "constants.h"
#include "scene.h"
#include "display.h"

const TVector black = TVector(0.25, 0.25, 0.25);
const TVector green = TVector(0, 1, 0);
const TVector red = TVector(1, 0, 0);
const TVector blue = TVector(0, 0, 1);
// the time step of the simulation
const sim_double dt = 0.05 * ns;

sim_double AmplModFunc(sim_double t)
{
	const sim_double tmax = 0.4 * ns;
	const sim_double tdf = 0.1 * ns;
	return exp(-pow(t - tmax, 2) / (2 * tdf * tdf));
}

int main()
{
	TScene scene;
	// fields with virtual test charges to represent the forces as functions of the location
	std::deque<TParticle*> PrimaryField;
	std::deque<TParticle*> SecondaryField;

	// create the transmitter
	TParticle* Transmitter = scene.Add_Particle();
	// convert the point charge into a Hertzian dipole
	Transmitter->ToHertzianDipole(mp, e, 1 * nm, 1 * GHz, 0, TVector(0, 0, 1), AmplModFunc);
	// make reflective
	Transmitter->MakeReflective(5e43, 0, 1000);
	// set position
	Transmitter->SetLinearTrajectory(TVector(-90 * cm, 0, 0), TVector(0.75 * c, 0, 0));

	// create a grid of test charges to represent the field generated by the transmitter
	for (int ix = -50; ix <= 50; ix++)
	{
		for (int iz = -50; iz <= 50; iz++)
		{
			TParticle* Probe = scene.Add_Probe(TVector(ix * 2 * cm, 0, iz * cm), TVector(0, 0, 0));
			PrimaryField.push_back(Probe);
			scene.Add_WeberMaxwellForce(Transmitter, Probe);
		}
	}

	// the reflector
	TParticle* Reflector = scene.Add_Particle();
	// convert the point charge into a Hertzian dipole
	Reflector->ToHertzianDipole(mp, e, 0, 0, 0, TVector(0, 0, 1), NULL);
	// make reflective
	Reflector->MakeReflective(5e43, 0, 1000);
	// set position
	Reflector->SetLinearTrajectory(TVector(0, 0, 20 * cm), TVector(0, 0, 0));

	// create a grid of test charges to represent the field generated by the receiver
	for (int ix = -50; ix <= 50; ix++)
	{
		for (int iz = -50; iz <= 50; iz++)
		{
			TParticle* Probe = scene.Add_Probe(TVector(ix * 2 * cm, 0, iz * cm), TVector(0, 0, 0));
			SecondaryField.push_back(Probe);
			scene.Add_WeberMaxwellForce(Reflector, Probe);
		}
	}

	// create electromagnetic force between transmitter and reflector
	scene.Add_WeberMaxwellForce(Reflector, Transmitter);

	// open a window to display the field and motion of the Hertzian dipole
	TDisplay display(700, 350, -100 * cm, -50 * cm, 100 * cm, 50 * cm, "Moving transmitter emits an EM pulse at 0.4 ns, which is then reflected by the stationary receiver");

	// simulate the fields and the motion of the Hertzian dipoles
	for (int i = 0; ; i++)
	{
		// time step
		scene.TimeStep(dt);

		// display simulation
		display.Clear();
		display.PlotForceFieldXZ(PrimaryField, i * dt, 1e16, 10, 10, black);
		display.PlotForceFieldXZ(SecondaryField, i * dt, 1e16, 10, 10, red);
		display.DrawTime(i * dt / ns, "ns", 1, blue);
		display.DrawParticle(Transmitter, i * dt, 5, green);
		display.DrawParticle(Reflector, i * dt, 5, blue);
		display.Draw(true);
	}

	return 0;
}
