/*
Copyright (c) 2023 by Steffen Kühn, steffen.kuehn@aurinovo.de

This file is part of OpenWME, an electromagnetic field solver based on
Weber-Maxwell electrodynamics.

OpenWME is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

OpenWME is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
*/

#include <stdio.h>
#include <math.h>
#include "constants.h"
#include "scene.h"
#include "display.h"

const TVector black = TVector(0.25, 0.25, 0.25);
const TVector red = TVector(1, 0, 0);
const TVector blue = TVector(0, 0, 1);
const sim_double maxtime = 20 * ns;
const sim_double dt = 0.05 * ns;
const sim_double vmax = 0.5 * c;
const sim_double t0 = 0.5 * ns;
const sim_double t1 = 2 * ns;
const sim_double x0 = 0 * m;
const sim_double c0 = -(t0*vmax) / (t1 - t0);
const sim_double c1 = vmax / (t1 - t0);
const sim_double x1 = c0 * t1 + (c1 * t1 * t1) / 2 - (t0 * t0 *vmax) / (2 * (t0 - t1)) + x0;

// trajectory
TVector trajectory0(sim_double t, TVector r0)
{
	if (t <= t0) return TVector(x0, 0, 0);
	if (t >= t1) return TVector(x1 + vmax * (t - t1), 0, 0);
	return TVector(x0 + c0 * t + (c1 * t * t) / 2 - (t0 * t0 * vmax) / (2 * (t0 - t1)), 0, 0);
}

// first derivative of the trajectory with respect to time
TVector trajectory1(sim_double t, TVector r0)
{
	if (t <= t0) return TVector(0, 0, 0);
	if (t >= t1) return TVector(vmax, 0, 0);
	return TVector(c0 + c1 * t, 0, 0);
}

// second derivative of the trajectory with respect to time
TVector trajectory2(sim_double t, TVector r0)
{
	if (t <= t0) return TVector(0, 0, 0);
	if (t >= t1) return TVector(0, 0, 0);
	return TVector(c1, 0, 0);
}

int main()
{
	TScene scene;
	std::deque<TParticle*> Field;

	// create the point charge (electron)
	TParticle* Electron = scene.Add_Particle();
	Electron->ToPointCharge(me, e);
	Electron->SetFixedTrajectory(TVector(0, 0, 0), trajectory0, trajectory1, trajectory2);

	// create a grid of test charges to represent the field generated by the point charge
	for (int ix = -50; ix <= 50; ix++)
	{
		for (int iz = -50; iz <= 50; iz++)
		{
			TParticle* Probe = scene.Add_Probe(TVector(ix * 10 * cm, 0, iz * 10 * cm), TVector(0, 0, 0));
			Field.push_back(Probe);
			scene.Add_WeberMaxwellForce(Electron, Probe);
		}
	}

	// open a window to display the field and motion of the particle
	TDisplay display(700, 700, -5 * m, -5 * m, 5 * m, 5 * m, "Suddenly accelerated point charge");

	// simulate the field step by step
	for (int i = 0; i * dt <= maxtime; i++)
	{
		// time step
		scene.TimeStep(dt);

		// display simulation
		display.Clear();
		display.PlotForceFieldXZ(Field, i * dt, 1e10, 10, 10, black);
		display.DrawTime(i * dt / ns, "ns", 1, red);
		display.DrawParticle(Electron, i * dt, 5, red);
		display.Draw(true);
	}

	return 0;
}
