/*
Copyright (c) 2023 by Steffen Kühn, steffen.kuehn@aurinovo.de

This file is part of OpenWME, an electromagnetic field solver based on
Weber-Maxwell electrodynamics.

OpenWME is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

OpenWME is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
*/

#include <stdio.h>
#include <math.h>
#include "constants.h"
#include "scene.h"
#include "display.h"

const TVector black = TVector(0.25, 0.25, 0.25);
const TVector green = TVector(0, 1, 0);
const TVector red = TVector(1, 0, 0);
const TVector blue = TVector(0, 0, 1);

const sim_double dt = 0.05 * ns;
const sim_double freq = 5 * GHz;
const sim_double amp = 100 * nm;
const sim_double charge = 1e14 * e;
const TVector direction = TVector(0, 0, 1);
const sim_double reflpara = 10000;
const sim_double mass = 1 * g;
const sim_double speed = -0.03 * c;
const sim_double start_z = 30 * cm;
const sim_double maxtime = (2 * nrm(start_z)) / nrm(speed);

sim_double AmplModFunc(sim_double t)
{
	if (t < 0) return 0;
	return 1;
}

int main()
{
	TScene scene;
	std::deque<TParticle*> PrimaryField;
	std::deque<TParticle*> SecondaryField;

	TParticle* Transmitter = scene.Add_Particle();
	Transmitter->ToHertzianDipole(mass, charge, amp, freq, 0, direction, AmplModFunc);
	Transmitter->SetLinearTrajectory(TVector(-30 * cm, 0, start_z), TVector(0, 0, speed));

	// create a grid of test charges to represent the field generated by the transmitter
	for (int ix = -35; ix <= 0; ix++)
	{
		for (int iz = -50; iz <= 50; iz++)
		{
			TParticle* Probe = scene.Add_Probe(TVector(ix * 1 * cm, 0, iz * cm), TVector(0, 0, 0));
			PrimaryField.push_back(Probe);
			scene.Add_WeberMaxwellForce(Transmitter, Probe);
		}
	}

	// the doubleslit
	std::deque<TParticle*> Doubleslit;
	for (int iz = -30; iz <= 30; iz++)
	{
		sim_double pz = iz * 3 * cm;

		if ((pz > 10 * cm) && (pz < 20 * cm)) continue;
		if ((pz < -10 * cm) && (pz > -20 * cm)) continue;
		TParticle* Reflector = scene.Add_Particle();
		Reflector->ToHertzianDipole(1, 1, 0, 0, 0, TVector(0, 0, 1), NULL);
		Reflector->MakeReflective(reflpara, 0, 1000);
		Reflector->SetLinearTrajectory(TVector(0, 0, iz * 3 * cm), TVector(0, 0, 0));
		Doubleslit.push_back(Reflector);
	}

	// create a grid of test charges to represent the field generated by the receiver
	for (int ix = -35; ix <= 0; ix++)
	{
		for (int iz = -50; iz <= 50; iz++)
		{
			TParticle* Probe = scene.Add_Probe(TVector(ix * 1 * cm, 0, iz * cm), TVector(0, 0, 0));
			SecondaryField.push_back(Probe);
			for (std::size_t j = 0; j < Doubleslit.size(); j++)
			{
				scene.Add_WeberMaxwellForce(Doubleslit[j], Probe);
			}
		}
	}

	// create electromagnetic forces between transmitter and doubleslit
	for (std::size_t j = 0; j < Doubleslit.size(); j++)
	{
		scene.Add_WeberMaxwellForce(Doubleslit[j], Transmitter);
	}

	// open a window to display the field and motion of the Hertzian dipole
	TDisplay display(350, 1000, -35 * cm, -50 * cm, 0 * cm, 50 * cm, "Interference at a double slit");

	// simulate the change of the field and the motion of the Hertzian dipole step by step
	for (int i = 0; i * dt < maxtime; i++)
	{
		// time step
		scene.TimeStep(dt);

		// display simulation
		display.Clear();
		display.PlotForceFieldXZ(PrimaryField, i * dt, 5e-3, 10, 10, black);
		display.PlotForceFieldXZ(SecondaryField, i * dt, 5e-1, 10, 10, red);
		display.DrawTime(i * dt / ns, "ns", 1, black);
		display.DrawParticle(Transmitter, i * dt, 5, green);
		for (std::size_t j = 0; j < Doubleslit.size(); j++)
		{
			display.DrawParticle(Doubleslit[j], i * dt, 5, blue);
		}
		display.Draw(true);
	}

	return 0;
}
