/*
Copyright (c) 2023 by Steffen Kühn, steffen.kuehn@aurinovo.de

This file is part of OpenWME, an electromagnetic field solver based on
Weber-Maxwell electrodynamics.

OpenWME is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

OpenWME is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
*/

#include <stdio.h>
#include <math.h>
#include "constants.h"
#include "scene.h"
#include "display.h"

const TVector black = TVector(0.25, 0.25, 0.25);
const TVector red = TVector(1, 0, 0);
const TVector blue = TVector(0, 0, 1);
// the time step of the simulation
const sim_double dt = 0.2 * ns;
// frequency (trajectory)
const sim_double freq = 50 * MHz;
// amplitude (trajectory)
const sim_double amp = 0.2 * m;
// zero vector
const TVector zero = TVector(0, 0, 0);

// trajectory
TVector trajectory0(sim_double t)
{
	return TVector(amp * sin(2 * pi * freq * t), 0, amp * sin(4 * pi * freq * t));
}

// first derivative of the trajectory with respect to time
TVector trajectory1(sim_double t)
{
	return TVector(2 * amp * freq * pi * cos(2 * freq * pi * t), 0, 4 * amp * freq * pi * cos(4 * freq * pi * t));
}

// second derivative of the trajectory with respect to time
TVector trajectory2(sim_double t)
{
	return TVector(-4 * amp * freq * freq * pi * pi * sin(2 * freq * pi * t), 0, -16 * amp * freq * freq * pi * pi * sin(4 * freq * pi * t));
}

int main()
{
	TScene scene;
	// to represent the forces as a function of location
	std::deque<TParticle*> Field;

	// create the point charge (electron)
	TParticle* Electron = scene.Add_Particle();
	Electron->ToPointCharge(me, e);
	// set trajectory
	Electron->SetFixedTrajectory(zero, trajectory0, trajectory1, trajectory2);

	// create a grid of test charges to represent the field generated by the transmitter
	for (int ix = -50; ix <= 50; ix++)
	{
		for (int iz = -50; iz <= 50; iz++)
		{
			TParticle* Probe = scene.Add_Probe(TVector(ix * 10 * cm, 0, iz * 10 * cm), TVector(0, 0, 0));
			Field.push_back(Probe);
			scene.Add_WeberMaxwellForce(Electron, Probe);
		}
	}

	// open a window to display the field and motion of the Hertzian dipole
	TDisplay display(700, 700, -5 * m, -5 * m, 5 * m, 5 * m, "Field of an electron moving on a non-trivial trajectory");

	// simulate the fields step by step
	for (int i = 0; ; i++)
	{
		// time step
		scene.TimeStep(dt);

		// display simulation
		display.Clear();
		display.PlotForceFieldXZ(Field, i * dt, 1e10, 10, 10, black);
		display.DrawTime(i * dt / ns, "ns", 1, red);
		display.DrawParticle(Electron, i * dt, 5, red);
		display.Draw(true);
	}

	return 0;
}
