/*
Copyright (c) 2023 by Steffen Kühn, steffen.kuehn@aurinovo.de

This file is part of OpenWME, an electromagnetic field solver based on
Weber-Maxwell electrodynamics.

OpenWME is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.

OpenWME is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
*/

#include <stdio.h>
#include <math.h>
#include "constants.h"
#include "scene.h"
#include "display.h"

const TVector black = TVector(0.25, 0.25, 0.25);
const TVector red = TVector(1, 0, 0);
// the time step of the simulation
const sim_double dt = 0.01 * ns;
// current strength
const sim_double current = 10 * A;
// number of current elements
const int segments = 100;
// radius of the Helmholtz coil
const sim_double radius = 18 * cm;
// frequency
const sim_double frequency = 500 * MHz;

int main()
{
	TScene scene;
	// container for the current elements that form the current loop
	std::deque<TParticle*> CurrentLoop;
	// a field with virtual test charges to represent the forces as a function of location
	std::deque<TParticle*> Field;

	// create the current loop
	for (int i = 0; i < segments; i++)
	{
		TParticle* MetallAtoms = scene.Add_Particle();
		TVector r(radius * sin(2 * pi / segments * i), 0, radius * cos(2 * pi / segments * i));
		TVector d(cos(2 * pi / segments * i), 0, -sin(2 * pi / segments * i));
		MetallAtoms->SetLinearTrajectory(r, TVector(0, 0, 0));
		MetallAtoms->ToACCurrentElement(1 * g, current, (2 * pi * radius) / segments, d, frequency, 0, NULL);
		CurrentLoop.push_back(MetallAtoms);
	}

	// create a grid of test charges to represent the field generated by the Hertzian dipole
	for (int ix = -10; ix <= 10; ix++)
	{
		for (int iz = -10; iz <= 10; iz++)
		{
			// a probe is a virtual point charge that can receive forces but does not generate
			// forces itself. Such objects do not exist in reality. They serve only for
			// visualization. Note that a probe can also have an instantaneous velocity and that
			// the perception of the field depends on it.
			TParticle* probe = scene.Add_Probe(TVector(ix * 5 * cm, 0, iz * 5 * cm), TVector(0, 0, 0));
			Field.push_back(probe);
		}
	}

	// define an electromagnetic force between each probe and the current loop
	for (std::size_t i = 0; i < CurrentLoop.size(); i++)
	{
		for (std::size_t j = 0; j < Field.size(); j++)
		{
			scene.Add_WeberMaxwellForce(CurrentLoop[i], Field[j]);
		}
	}

	// open a window to display the the setup
	TDisplay display(700, 700, -50 * cm, -50 * cm, 50 * cm, 50 * cm, "Field of current loop with alternating current");

	for (int i = 0; ; i++)
	{
		// time step
		scene.TimeStep(dt);

		// display simulation
		display.Clear();

		display.PlotForceFieldXZ(Field, i * dt, 3e-3, 10, 10, black);
		display.DrawTime(i * dt / ns, "ns", 1, black);

		// show current loop with current direction
		for (std::size_t j = 0; j < CurrentLoop.size(); j++)
		{
			display.DrawParticle(CurrentLoop[j], 0, 7, black);
		}
		for (std::size_t j = 0; j < CurrentLoop.size(); j++)
		{
			display.PlotVector(CurrentLoop[j]->GetVelocityCurElem(i * dt) * 10, CurrentLoop[j]->GetPosition(i * dt), 10, 10, red);
		}

		display.Draw(true);
	}

	return 0;
}
